name: Build & publish package

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write

jobs:
  Publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test results
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true

    - name: See path
      run: pwd

    - name: Find package file test
      run: find . -name '*.nupkg'

    - name: Find package file
      run: echo "package = `find . -name '*.nupkg'`" >> $GITHUB_ENV

    - run: echo "${{ env.package }}" 

#    - name: Publish
#      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
