name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
